stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

# 编译步骤
mvn-build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    ## 打包 Service Project 为 jar包， 同时在测试过程中激活test profile（这里是maven的test profile，区别于springboot的profile）
    - mvn clean package -Ptest
    - echo "build complete."
    - ls ./target
  cache:
    - paths:
        - ./target
  artifacts:
    paths:
      - target/*.jar
# 构建镜像步骤
make-deploy-image-job:
  stage: deploy
  only:
    - main # 仅在 main 分支触发
  needs:
    - mvn-build-job
  script:
    - mkdir docker/service/build
    - bash ./docker/service/docker-image-build.sh
    - echo "Compile ok!"
# 部署步骤
deploy-job:
  stage: deploy
  only:
    - main # 仅在 dev 分支触发
  needs:
    - make-deploy-image-job
  script:
    - mkdir -p docker/service/config
    - cp config/application.yml docker/service/config/application.yml
    - cp config/application-test.yml docker/service/config/application-test.yml
    - cd docker/service/ && bash docker-run.sh
    - CONTAINER_ID=springboot-init
    - sleep 30
    - docker inspect -f '{{.State.Running}}' $CONTAINER_ID | grep true || (echo "Container is not running" && docker logs $CONTAINER_ID && exit 1)
    - echo "Container is running"
    - echo "Run ok!"