## !! logback configuration
logging:
  file:
    name:
      logs/runtime.log
  logback:
    rolling policy:
      file-name-pattern: logs/web-service.%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB # 大小限制10MB,超过会自动切割
      max-history: 30 # 最多保留30天的日志
