# 公共配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
spring:
  application:
    name: springboot-init
  # 默认 dev 环境.根据配置加载prod还是test环境，如有相同，则采取覆盖策略
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.123.81:33306/my_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 # 初始化连接数
      min-idle: 5 # 最少空闲连接数
      max-active: 20 # 最大连接数
      max-wait: 60000 # 获取连接的最大等待时间，60s
      time-between-eviction-runs-millis: 60000 # 每隔 60000 毫秒（60 秒），Druid 会检查并回收空闲连接
      min-evictable-idle-time-millis: 300000 # 连接在池中最小生存的时间，5 min
      validation-query: SELECT 1 FROM DUAL # 用来检测连接是否有效的 SQL
      test-while-idle: true # 申请连接的时候检测有效性
      pool-prepared-statements: true # 缓存预处理语句，提升性能
      max-pool-prepared-statement-per-connection-size: 20 # 每个连接最多缓存多少个预处理语句
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  # Redis 配置
  redis:
    cluster:
      nodes: # 集群节点列表
        - 192.168.123.81:6371
        - 192.168.123.81:6372
        - 192.168.123.81:6373
        - 192.168.123.81:6374
        - 192.168.123.81:6375
        - 192.168.123.81:6376
      max-redirects: 4 # 最大重定向次数
    lettuce: # 使用 Lettuce 连接池（默认）
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8 # 最大空闲连接数
        min-idle: 0 # 最小空闲连接数
        max-wait: -1 # 最大等待时间（毫秒，-1 表示无限等待）
    password: 123456 # Redis 密码
    database: 0 # Redis 数据库索引
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: http://192.168.123.81:9200,192.168.123.81:9201,192.168.123.81:9202
    username: elastic
    password: B6kUdGhUzmhTxpcJ7RS6
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx

security:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    secret-key: itcast
    # 设置jwt过期时间
    ttl: 7200000
    # 设置前端传递过来的令牌名称
    token-name: Authentication
    # token 前缀
    token-prefix: Bearer
    # claims-用户名
    claims-username: userAccount

