spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.123.81:33306/my_db?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  # Redis 配置
  redis:
    cluster:
      nodes: # 集群节点列表
        - 192.168.123.81:6371
        - 192.168.123.81:6372
        - 192.168.123.81:6373
        - 192.168.123.81:6374
        - 192.168.123.81:6375
        - 192.168.123.81:6376
      max-redirects: 4 # 最大重定向次数
    password: 123456 # Redis 密码
    database: 0 # Redis 数据库索引
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: http://192.168.123.81:9200,192.168.123.81:9201,192.168.123.81:9202
    username: elastic
    password: B6kUdGhUzmhTxpcJ7RS6

# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: 127.0.0.1
        port: 6379
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx


